name: purge of Images

on: [push]
  #workflow_dispatch:
  

jobs:
  download_image_name_file:
    name: download image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: list files
      run: | 
           cat value
           ls -R
           sed -i '1,13d' value
           cat value
           sed 's/ //g' value > value1
           sed -i -e 's/^/abc./' value1
           cat value1
           sed 's/"//g' value1 > value2
           cat value2
           cut -d ":" -f 1 value2 > value3
           cut -d ":" -f 2 value2 > value4
           cat value3
           cat value4
    - name: Azure PowerShell script
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: |       
            az login --service-principal -u 0c9329ee-fef9-4f31-815b-c1e1a38e43b9 -p pdC8Q~tkSbbuCFfaqkjErMMOYY7z2F5_Wbr.MdmG --tenant 05b6ac85-4b5b-4e98-a644-0901baef399d
            $registryName = 'Dockerimages11'
            $donotdeleterepo = Get-Content value3
            $donotdeleterepotags = Get-Content value4
            $repoArray = (az acr repository list --name $registryName --output json | ConvertFrom-Json)
            $a=0
            foreach ($repo1 in $donotdeleterepo){
             foreach ($repo in $repoArray){           
              if ($repo1 -eq $repo){
              $tagsArray = (az acr repository show-tags --name $registryName --repository $repo1 --orderby time_asc --output json | ConvertFrom-Json )
              $tag1=$donotdeleterepotags[$a]      
               foreach($tag in $tagsArray){                                     
                 if ($tag1 -eq $tag){
                  $a++
                   echo "This tag will NOT be deleted -- $repo : $tag"
                  }
                else
                 {
                   echo "this will be deleted -- $repo : $tag"
                   #az acr repository untag -n Dockerimages11 --image nginx:latest
                 }
                 }}
              else
               { }               
               }}
