name: purge of Images

on:
  workflow_dispatch:

jobs:
  download_image_name_file:
    name: download image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Download files
      uses: actions/download-artifact@v4
      with:
        name: value
        path: tmp/
    - name: Display structure of downloaded files
      run: ls -R tmp
