name: purge of Images

on: [push]
  #workflow_dispatch:
  

jobs:
  download_image_name_file:
    name: download image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: list files
      run: | 
           cat value
           ls -R
           sed -i '1,13d' value
           cat value
           sed 's/ //g' value > value1
           sed -i -e 's/^/abc./' value1
           cat value1
           sed 's/"//g' value1 > value2
           cat value2
           cut -d ":" -f 1 value2 > value3
           cut -d ":" -f 2 value2 > value4
           cat value3
           cat value4
  setup_up_AKS:
    runs-on: ubuntu-latest
    needs:
      - download_image_name_file
    steps:
      - uses: actions/checkout@v2
      - uses: elstudio/action-install-azure-cli@v1
      - name: 'Preparation'
        run: |
          echo "Set Cloud to AzureCloud"
          az cloud set --name AzureCloud
          echo "Login to Azure"
          az login --service-principal -u afbaig19@gmail.com -p Faz@l786 --tenant 05b6ac85-4b5b-4e98-a644-0901baef399d
          az acr repository list --name $registryName --output json | ConvertFrom-Json
