name: purge of Images

on:
  workflow_dispatch:

jobs:
  download_image_name_file:
    name: download image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: list files
      run: | 
           cat value
           ls -R
           sed -i '11,13d' value
           cat value
