name: infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: testing
        required: true
        default: 'EMEA_DEV'
        type: choice
        options:
          - EMEA_DEV
          - AMER_INT
env:
  GH_RUNNER_NAME: ${{ vars.GH_RUNNER_NAME }}
  TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}        
jobs:
  download_image_name_file:
    name: Overview Environment Variables
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3          
    - name: echo
      run: |
           echo "Environment: ${{ github.event.inputs.environment }}"
           echo "Github Runner Label to run on: ${{ github.event.inputs.environment }}"
           echo "Terraform version: ${{ env.TERRAFORM_VERSION }}"    
  
    
          
