name: infra

on:
  workflow_dispatch:
    inputs:
      environment: 
        description: testing
        required: true
        type: choice
        options:
         - EMEA_DEV
         - AMER_INT
       
jobs:
  download_image_name_file:
    name: Overview Environment Variables
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest     
    steps:
      - name: echo
        run: |
           echo "Environment: ${{ github.event.inputs.environment }}"
           echo "Github Runner Label to run on: ${{ github.event.inputs.environment }}"
           echo "Terraform version: ${{ env.TERRAFORM_VERSION }}"    

  
    
          
